/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * The department document register: what each department's library holds, derived from the real
 * published documents in `public/department-corpus/<departmentId>.json` by
 * `scripts/build-department-register.mjs`.
 *
 * WHY IT IS GENERATED. A screen must know a department's documents the instant it draws, but the
 * documents' own text is far too large to load for that (125 documents, about 9 MB). The text stays in
 * the corpus, read only when the wording is needed; this file carries the register every screen needs.
 * Because it is produced from the corpus rather than typed by hand, the register and the documents
 * cannot drift apart — `npm run validate` re-runs the generator and fails the build if they do.
 *
 * Every value below is copied from the corpus, which was built from the body that published each
 * document. Nothing here is invented, and a document whose text could not be read is recorded as
 * `read: false` with no characters, never quietly dropped.
 */

import type { DepartmentDocument, DepartmentId } from "./departments";

/** Every department's published documents, keyed by department id. */
export const DEPARTMENT_DOCUMENTS: Record<DepartmentId, readonly DepartmentDocument[]> = {
  agri: [
    {
      id: "agri-001",
      section: "Committee report",
      title: "Report of the Lands, Agriculture Committee on the State of Food Security in the Country",
      publisher: "Parliament of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Lands%2C%20Agric%20Committee-Report%20on%20Food%20Security.pdf",
      pages: 10,
      read: true,
      characters: 17698,
    },
    {
      id: "agri-002",
      section: "Public accounts",
      title: "Third Report of the Public Accounts Committee on the Special Maize Programme / Command Agriculture (S.C. 24, 2021)",
      publisher: "Parliament of Zimbabwe",
      date: "August 2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/PAC%20Report%20-%20Command%20Agriculture%20Special%20Maize%20Programme%20SC%2024%202021.pdf",
      pages: 35,
      read: true,
      characters: 69202,
    },
    {
      id: "agri-003",
      section: "Public accounts",
      title: "Second Report of the Public Accounts Committee on Vote 8, Ministry of Lands, Agriculture, Water, Fisheries and Rural Resettlement for the years ended 2017 and 2018",
      publisher: "Parliament of Zimbabwe",
      date: "April 2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Min.%20of%20Lands%2C%20Agriculture%20separate.pdf",
      pages: 19,
      read: true,
      characters: 40933,
    },
    {
      id: "agri-004",
      section: "Public accounts",
      title: "Report of the Public Accounts Committee on the Audited Financial Statements for the Agricultural and Rural Development Authority, 2023",
      publisher: "Parliament of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/PAC%20REPORT%20ON%20AUDITED%20FINANCIAL%20STATEMENTS%20FOR%20ARD.pdf",
      pages: 5,
      read: true,
      characters: 6415,
    },
    {
      id: "agri-005",
      section: "Committee report",
      title: "First Report of the Thematic Committee on Peace and Security on the Preparedness of the Grain Marketing Board for the 2016/2017 Grain Deliveries (S.C. 15, 2017)",
      publisher: "Parliament of Zimbabwe",
      date: "July 2017",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Peace%20and%20Security%201st%20Report%20on%20Preparedness%20of%20the%20%28GMB%29%20to%20Handle%20the%202016-17%20Grain%20Deliveries%20and%20the%20Success%20of%20the%20Command%20Agriculture%20Programme.pdf",
      pages: 12,
      read: true,
      characters: 19285,
    },
    {
      id: "agri-006",
      section: "Committee report",
      title: "First Report of the Portfolio Committee on Lands, Agriculture, Water, Fisheries and Rural Development on the Case of US$28.2 million distributed by the Reserve Bank to Grain Millers",
      publisher: "Parliament of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/GRAIN%20MILLERS%20REPORTElusive%20US%2428.2m.pdf",
      pages: 17,
      read: true,
      characters: 33009,
    },
    {
      id: "agri-007",
      section: "Governing law",
      title: "Agricultural Marketing Authority (Grain, Oil Seeds and Products) (Amendment) Regulations, 2021 (No. 1)",
      publisher: "Government of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202021-274%20Agricultural%20Marketing%20Authority%20%28Grain%2C%20Oil%20Seeds%20and%20Products%29%20%28Amendment%29%20Regulations%2C%202021%28No.%201%29.pdf",
      pages: 6,
      read: true,
      characters: 9826,
    },
    {
      id: "agri-008",
      section: "Governing law",
      title: "Tobacco Industry and Marketing (Prohibition of Side Marketing) Regulations, 2022",
      publisher: "Government of Zimbabwe",
      date: "2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202022-077%20Tobacco%20Industry%20and%20Marketing%20%28Prohibition%20of%20Side%20Marketing%29%20Regulations%2C%202022_0.pdf",
      pages: 10,
      read: true,
      characters: 15622,
    },
  ],
  def: [
    {
      id: "def-001",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Defence, Home Affairs, Security Services and War Veterans' Affairs on the Petition from the Zimbabwe National Association of Liberation War Veteran Cadres Regarding the Amendment of the Veterans of the Liberation Struggle Act (S.C. 35, 2025)",
      publisher: "Parliament of Zimbabwe",
      date: "2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REPORT%20ON%20THE%20PETITION%20FROM%20THE%20ZIMBABWE%20NATIONAL%20ASSOCIATION%20OF%20LIBERATION%20WAR%20VETERAN%20CADRES%20REGARDING%20THE%20AMENDMENT%20OF%20THE%20VETERANS%20OF%20THE%20LIBERATION%20STRUGGLE%20ACT.pdf",
      pages: 10,
      read: true,
      characters: 21969,
    },
    {
      id: "def-002",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Defence, Home Affairs, Security Services and War Veterans' Affairs on the Petition from the Children of War Veterans and Heroes' Dependants Forum on Economic Empowerment for War Veterans and their Dependants (S.C. 5, 2024)",
      publisher: "Parliament of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Report%20on%20Chidren%20of%20War%20Veterans%20Petition.pdf",
      pages: 11,
      read: true,
      characters: 21966,
    },
    {
      id: "def-003",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Defence, Home Affairs, Security Services and War Veterans' Affairs on Statelessness of Migrants in Zimbabwe (S.C. 13, 2024)",
      publisher: "Parliament of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Report%20on%20Statelessness%20of%20Migrants%20in%20Zimbabwe-Defence%20Committee.pdf",
      pages: 13,
      read: true,
      characters: 24448,
    },
    {
      id: "def-004",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Defence, Home Affairs, Security Services and War Veterans' Affairs on the Petition from Sam Parerenyatwa on Exhumation and Decent Reburials of Heroes and Heroines who Perished during the Liberation Struggle (S.C. 6, 2024)",
      publisher: "Parliament of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Petition%20Report%20for%20Cde%20Sam%20Parerenyatwa%20%27s%20Petition.pdf",
      pages: 9,
      read: true,
      characters: 15501,
    },
    {
      id: "def-005",
      section: "Regulations",
      title: "Defence (Regular Force) (Officers) (Amendment) Regulations, 2024 (No. 5) — S.I. 199 of 2024",
      publisher: "Government of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202024-199%20Defence%20%28Regular%20Force%29%20%28Officers%29%20%28Amendment%29%20Regulations%2C%202024%20%28No.%205%29.pdf",
      pages: 2,
      read: true,
      characters: 3837,
    },
    {
      id: "def-006",
      section: "Regulations",
      title: "Defence (Regular Force) (Non-Commissioned Members) (Amendment) Regulations, 2024 (No. 8) — S.I. 198 of 2024",
      publisher: "Government of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202024-198%20Defence%20%28Regular%20Force%29%20%28Non-Commissioned%20Members%29%20%28Amendment%29%20Regulations%2C%202024%20%28No.%208%29.pdf",
      pages: 2,
      read: true,
      characters: 2352,
    },
    {
      id: "def-007",
      section: "General notice",
      title: "Extension of Term of the Commander of the Zimbabwe Defence Forces — General Notice 15 of 2025, under the Defence Act [Chapter 11:02]",
      publisher: "Government of Zimbabwe",
      date: "2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/GN%202025-0005%20Extension%20of%20Term%20of%20the%20Commander%20of%20the%20Zimbabwe%20Defence%20Forces.pdf",
      pages: 1,
      read: true,
      characters: 829,
    },
    {
      id: "def-008",
      section: "Bill",
      title: "Zimbabwe National Defence University Bill, 2015 (H.B. 12, 2015)",
      publisher: "Government of Zimbabwe",
      date: "2015",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Zimbabwe%20National%20Defence%20University%20-%20HB%2012-2015.pdf",
      pages: 27,
      read: true,
      characters: 64535,
    },
  ],
  edu: [
    {
      id: "edu-001",
      section: "Governing law",
      title: "Education Amendment Act, 2019 (Act 15 of 2019)",
      publisher: "Government of Zimbabwe",
      date: "2019",
      url: "https://www.veritaszim.net/sites/veritas_d/files/EDUCATION%20AMENDMENT%20ACT%2C%202019%20%5B%20Act%2015-2019%5D_0.pdf",
      pages: 6,
      read: true,
      characters: 12379,
    },
    {
      id: "edu-002",
      section: "Audit report",
      title: "Auditor-General's Report on Registration, Supervision and Monitoring of Schools and Independent Colleges",
      publisher: "Auditor-General, Republic of Zimbabwe",
      date: "2020",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REGISTRATION%2C%20SUPERVISION%20AND%20MONITORING%20OF%20SCHOOLS%20%281%29.pdf",
      pages: 69,
      read: true,
      characters: 112283,
    },
    {
      id: "edu-003",
      section: "Committee report",
      title: "Report on the Verification Visit to Schools 2022",
      publisher: "Parliament of Zimbabwe",
      date: "2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REPORT%20ON%20THE%20VERIFICATION%20VISIT%20TO%20SCHOOLS%202022.pdf",
      pages: 16,
      read: true,
      characters: 32920,
    },
    {
      id: "edu-004",
      section: "Committee report",
      title: "First Report of the Portfolio Committee on Primary and Secondary Education on the Inclusive Education Policy (IEP) and Better Schools Programme Zimbabwe (BSPZ) Petitions",
      publisher: "Parliament of Zimbabwe",
      date: "May 2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/FIRST%20REPORT%20OF%20THE%20PORTFOLIO%20COMMITTEE%20ON%20PRIMARY%20AND%20SECONDARY%20EDUCATION%20ON%20THE%20INCLUSIVE%20EDUCATION%20POLICY%20%28IEP%29%20AND%20BETTER%20SCHOOLS%20PROGRAMME-%20ZIMBABWE%20%28BSPZ%29%20PETITIONS.pdf",
      pages: 9,
      read: true,
      characters: 19309,
    },
    {
      id: "edu-005",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Primary and Secondary Education on Benchmarking Visits to Kenya, Zambia and Ghana on Education Financing",
      publisher: "Parliament of Zimbabwe",
      date: "May 2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/PC%20on%20PSEducation%20-%20Report%20on%20Benchmarking%20Visits%20to%20Kenya%2C%20Zambia%20%26%20Ghana%20on%20Education%20Financing.pdf",
      pages: 13,
      read: true,
      characters: 34889,
    },
    {
      id: "edu-006",
      section: "Committee report",
      title: "Report on the Learning and Exchange Visit on the Finnish Early Childhood Education and Care Model",
      publisher: "Parliament of Zimbabwe",
      date: "2023",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Report%20on%20Early%20Childhood%20Education%20-%20Finland%20%26%20Sweden.pdf",
      pages: 12,
      read: true,
      characters: 28389,
    },
    {
      id: "edu-007",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Primary and Secondary Education on Schools Opening in Light of the COVID-19 Pandemic",
      publisher: "Parliament of Zimbabwe",
      date: "2020",
      url: "https://www.veritaszim.net/sites/veritas_d/files/PPC%20Pri%20and%20Sec%20Edu%20-%20Schools%20Opening%20Report.pdf",
      pages: 14,
      read: true,
      characters: 36870,
    },
    {
      id: "edu-008",
      section: "Governing law",
      title: "Education, Innovation, Research and Development Centre Act, 2021 (No. 3 of 2021)",
      publisher: "Government of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Centre%20for%20Education%2C%20Innovation%2C%20Research%20and%20Development%20Act%20No.%203%20of%202021.pdf",
      pages: 16,
      read: true,
      characters: 35275,
    },
  ],
  energy: [
    {
      id: "energy-001",
      section: "Governing law",
      title: "Electricity Act [Chapter 13:19]",
      publisher: "Government of Zimbabwe",
      date: "Published copy 2022-09",
      url: "https://www.veritaszim.net/sites/veritas_d/files/ELECTRICITY%20ACT%20CHAPTER%2013-19.pdf",
      pages: 30,
      read: true,
      characters: 130847,
    },
    {
      id: "energy-002",
      section: "Governing law",
      title: "Electricity Amendment Act, Act No. 7 of 2023",
      publisher: "Government of Zimbabwe",
      date: "2023",
      url: "https://www.veritaszim.net/sites/veritas_d/files/ELECTRICITY%20AMENDMENT%20ACT%2C%20Act%20No.%207%20of%202023%20.pdf",
      pages: 2,
      read: true,
      characters: 2633,
    },
    {
      id: "energy-003",
      section: "Regulations",
      title: "Electricity (Provision of Backbone Infrastructure) Regulations, 2026 (S.I. 128 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-128%20Electricity%20%28Provision%20of%20Backbone%20Infrastructure%29%20Regulations%2C%202026.pdf",
      pages: 12,
      read: true,
      characters: 17905,
    },
    {
      id: "energy-004",
      section: "Regulations",
      title: "Electricity (Own Consumption Undertakings Licensing Capacity) Regulations, 2026 (S.I. 126 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-126%20Electricity%20%28Own%20Consumption%20Undertakings%20Licensing%20Capacity%29%20Regulations%2C%202026.pdf",
      pages: 4,
      read: true,
      characters: 6336,
    },
    {
      id: "energy-005",
      section: "Regulations",
      title: "Electricity (Minimum Energy Performance Standards for Appliances and Labelling) Regulations, 2026 (S.I. 119 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-119%20Electricity%20%28Minimum%20Energy%20Performance%20Standards%20for%20Appliances%20and%20Labelling%29%20Regulations%2C%202026.pdf",
      pages: 8,
      read: true,
      characters: 11874,
    },
    {
      id: "energy-006",
      section: "Regulations",
      title: "Electricity (Licensing) (Amendment) Regulations, 2026 (S.I. 125 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-125%20Electricity%20%28Licensing%29%20%28Amendment%29%20Regulations%2C%202026.pdf",
      pages: 4,
      read: true,
      characters: 4643,
    },
    {
      id: "energy-007",
      section: "Regulations",
      title: "Electricity (Energy Management) Regulations, 2026 (S.I. 122 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-122%20Electricity%20%28Energy%20Management%29%20Regulations%2C%202026.pdf",
      pages: 26,
      read: true,
      characters: 47321,
    },
    {
      id: "energy-008",
      section: "Regulations",
      title: "Electricity (Electric Vehicle Charging Station Safety) Regulations, 2026 (S.I. 120 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-120%20Electricity%20%28Electric%20Vehicle%20Charging%20Station%20Safety%29%20Regulations%2C%202026.pdf",
      pages: 10,
      read: true,
      characters: 16457,
    },
  ],
  env: [
    {
      id: "env-001",
      section: "Governing law",
      title: "Forest Amendment Act, 2021 (Act No. 4 of 2021)",
      publisher: "Government of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Forest%20Amendment%20Act%204%20of%202021.pdf",
      pages: 8,
      read: true,
      characters: 20843,
    },
    {
      id: "env-002",
      section: "Governing law",
      title: "Parks and Wildlife Amendment Act, 2025 (Act No. 4 of 2025)",
      publisher: "Government of Zimbabwe",
      date: "2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Parks%20and%20Wildlife%20Amendment%20Act%20No.%204%20of%202025.pdf",
      pages: 56,
      read: true,
      characters: 148735,
    },
    {
      id: "env-003",
      section: "Regulations",
      title: "Environmental Management (Environmental Liability Polluter Pays) Regulations, 2026 (S.I. 92 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-092%20Environmental%20Management%20%28Environmental%20Liability%20Polluter%20Pays%29%20Regulations%2C%202026.pdf",
      pages: 4,
      read: true,
      characters: 4890,
    },
    {
      id: "env-004",
      section: "Regulations",
      title: "Environmental Management (Control of Alluvial Mining) (Amendment) Regulations, 2024 (No. 3) (S.I. 188 of 2024)",
      publisher: "Government of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202024-188%20Environmental%20Management%20%28Control%20of%20Alluvial%20Mining%29%20%28Amendment%29%20Regulations%2C%202024%20%28No.%203%29.pdf",
      pages: 4,
      read: true,
      characters: 6747,
    },
    {
      id: "env-005",
      section: "Regulations",
      title: "Carbon Trading (General) Regulations, 2025 (S.I. 48 of 2025)",
      publisher: "Government of Zimbabwe",
      date: "2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202025-048%20Carbon%20Trading%20%28General%29%20Regulations%2C%202025.pdf",
      pages: 92,
      read: true,
      characters: 144041,
    },
    {
      id: "env-006",
      section: "Regulations",
      title: "Environmental Management (Prohibition and Control of Ozone Depleting Substances, Greenhouse Gases and Dependent Equipment) Regulations, 2023 (S.I. 49 of 2023)",
      publisher: "Government of Zimbabwe",
      date: "2023",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202023-049%20Environmental%20Management%20%28Prohibition%20and%20Control%20of%20Ozone%20Depleting%20Substances%2C%20Greenhouse%20Gases%2C%20Ozone%20Depleting%20Substances%20and%20Greenhouse%20Gases%20Dependent%20Equipment%29%20Regulations%2C%202023.pdf",
      pages: 28,
      read: true,
      characters: 47334,
    },
    {
      id: "env-007",
      section: "Bill",
      title: "Environmental Management Amendment Bill, 2026 (H.B. 5, 2026)",
      publisher: "Parliament of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Environmental%20Management%20Amendment%20Bill%2C%202026%20H.B.%205%2C%202026.pdf",
      pages: 40,
      read: true,
      characters: 95382,
    },
    {
      id: "env-008",
      section: "Audit",
      title: "Auditor-General's Report on Protection of Wetlands by the Environmental Management Agency",
      publisher: "Auditor-General of Zimbabwe",
      date: "Published copy 2022-02",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Report%20on%20Protection%20of%20Wetlands%20by%20EMA.pdf",
      pages: 92,
      read: true,
      characters: 180944,
    },
  ],
  fin: [
    {
      id: "fin-001",
      section: "Governing law",
      title: "Public Debt Management Act [Chapter 22:21] (Act 4 of 2015)",
      publisher: "Government of Zimbabwe",
      date: "2015",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Public%20Debt%20Management%20Act%2C%20Act%204-2015.pdf",
      pages: 17,
      read: true,
      characters: 42637,
    },
    {
      id: "fin-002",
      section: "Governing law",
      title: "Finance Act, 2025 (Act No. 7 of 2025)",
      publisher: "Government of Zimbabwe",
      date: "2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Finance%20Act%2C%20Act%20No.%207%20of%202025.pdf",
      pages: 48,
      read: true,
      characters: 127063,
    },
    {
      id: "fin-003",
      section: "Annual report",
      title: "Annual Report of the Financial Intelligence Unit, 2024",
      publisher: "Financial Intelligence Unit, Reserve Bank of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Annual%20Report%20of%20Financial%20Intelligence%20Unit%202024_1.pdf",
      pages: 54,
      read: true,
      characters: 85529,
    },
    {
      id: "fin-004",
      section: "Governing law",
      title: "Public Procurement and Disposal of Public Assets Act [Chapter 22:23]",
      publisher: "Government of Zimbabwe",
      date: "2017",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Public%20Procurement%20Act%20r.pdf",
      pages: 70,
      read: true,
      characters: 193803,
    },
    {
      id: "fin-005",
      section: "Public finance statement",
      title: "Statement of Public Debt, 25 November 2021",
      publisher: "Ministry of Finance, Economic Development and Investment Promotion",
      date: "25 November 2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Statement%20of%20Public%20Debt-%2025%20November%202021.pdf",
      pages: 45,
      read: true,
      characters: 109743,
    },
    {
      id: "fin-006",
      section: "Monetary policy",
      title: "2025 Monetary Policy Statement",
      publisher: "Reserve Bank of Zimbabwe",
      date: "6 February 2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/MPS%20February%2006%202025.pdf",
      pages: 76,
      read: true,
      characters: 108433,
    },
    {
      id: "fin-007",
      section: "Governing law",
      title: "Money Laundering and Proceeds of Crime Amendment Act",
      publisher: "Government of Zimbabwe",
      date: "2019",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Money%20Laundering%20and%20Proceeds%20of%20Crime%20Amendment%20Act.pdf",
      pages: 14,
      read: true,
      characters: 30514,
    },
    {
      id: "fin-008",
      section: "National strategy",
      title: "Interim Poverty Reduction Strategy Paper (I-PRSP) 2016–2018",
      publisher: "Government of Zimbabwe",
      date: "2016",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Interim%20Poverty%20Reduction%20Strategy%20Paper%20%28I-PRSP%29%202016%20-%202018.pdf",
      pages: 224,
      read: true,
      characters: 304059,
    },
  ],
  health: [
    {
      id: "health-001",
      section: "Governing law",
      title: "Public Health Act [Chapter 15:17]",
      publisher: "Government of Zimbabwe",
      date: "2018",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Public%20Health%20Act%20%5BCHAPTER%2015-17%5Dr.pdf",
      pages: 76,
      read: true,
      characters: 210018,
    },
    {
      id: "health-002",
      section: "Governing law",
      title: "Health Service Act [Chapter 15:16] as at 1 June 2021",
      publisher: "Government of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Health%20Service%20Act%20%5BCap%2015-16%5D%20as%20amended%201%20June%202021.pdf",
      pages: 15,
      read: true,
      characters: 57934,
    },
    {
      id: "health-003",
      section: "Statistics",
      title: "Zimbabwe Demographic and Health Survey 2023–24",
      publisher: "Zimbabwe National Statistics Agency (ZIMSTAT)",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Zim%20Demographi%26%20Health%20Survey%202023-4.pdf",
      pages: 615,
      read: true,
      characters: 1284782,
    },
    {
      id: "health-004",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Health and Child Care on Prevention and Management of Non-Communicable Diseases including Cancer",
      publisher: "Parliament of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Report%20on%20Prevention%20and%20Management%20of%20NCDs%20including%20Cancer.pdf",
      pages: 10,
      read: true,
      characters: 16504,
    },
    {
      id: "health-005",
      section: "Committee report",
      title: "First Report of the Portfolio Committee on Health and Child Care on the Evidence Gathered during the Public Hearings on the Health Services Amendment Bill [H.B. 8, 2021]",
      publisher: "Parliament of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/FIRST%20REPORT%20OF%20THE%20PORTFOLIO%20COMMITTEE%20ON%20HEALTH%20AND%20CHILD%20CARE%20ON%20THE%20EVIDENCE%20GATHERED%20DURING%20THE%20PUBLIC%20HEARINGS%20ON%20THE%20HEALTH%20SERVICES%20AMENDMENT%20BILL%20%5BH.B%208%2C%202021%5D.pdf",
      pages: 6,
      read: true,
      characters: 12999,
    },
    {
      id: "health-006",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Health and Child Care on the Roles and Responsibilities of Village Health Workers",
      publisher: "Parliament of Zimbabwe",
      date: "2017",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Portfolio%20Committee%20on%20Health%20%26%20Child%20Care%20on%20the%20Roles%20%26%20Responsibilities%20of%20the%20Village%20Health%20Workers..pdf",
      pages: 18,
      read: true,
      characters: 36244,
    },
    {
      id: "health-007",
      section: "Committee report",
      title: "Special Report of the Portfolio Committee on Health on Putting Tuberculosis on the Political Agenda (S.C. 3, 2015)",
      publisher: "Parliament of Zimbabwe",
      date: "2015",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SC%202015-03%20-%20Special%20Report%20of%20the%20Portfolio%20Committee%20on%20Health%20on%20Putting%20Tuberculosis%20on%20the%20Political%20Agenda.pdf",
      pages: 13,
      read: true,
      characters: 22502,
    },
    {
      id: "health-008",
      section: "Treaty",
      title: "African Union Treaty for the Establishment of the African Medicines Agency",
      publisher: "African Union",
      date: "2019",
      url: "https://www.veritaszim.net/sites/veritas_d/files/36892-sl-TREATY_FOR_THE_ESTABLISHMENT_OF_THE_AFRICAN_MEDICINES_AGENCY.pdf",
      pages: 2,
      read: true,
      characters: 2044,
    },
  ],
  hedu: [
    {
      id: "hedu-001",
      section: "Governing law",
      title: "Manpower Planning and Development Amendment Act, 2020",
      publisher: "Government of Zimbabwe",
      date: "2020",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Manpower%20Planning%20and%20Development%20Amendment%20Act.pdf",
      pages: 20,
      read: true,
      characters: 46721,
    },
    {
      id: "hedu-002",
      section: "Governing law",
      title: "Marondera University of Agricultural Sciences and Technology Act [Chapter 25:29]",
      publisher: "Government of Zimbabwe",
      date: "2015",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Marondera%20University%20of%20Agricultural%20Sciences%20%26%20Technological%20Act%20%5BCap%2025-29%5D.pdf",
      pages: 28,
      read: true,
      characters: 64936,
    },
    {
      id: "hedu-003",
      section: "Governing law",
      title: "Pan-African Minerals University of Science and Technology Act [Chapter 25:33]",
      publisher: "Government of Zimbabwe",
      date: "2016",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Pan-African%20Minerals%20University%20of%20Science%20and%20Technology%20Act%20%5BCap%2025-33%5D.pdf",
      pages: 25,
      read: true,
      characters: 63943,
    },
    {
      id: "hedu-004",
      section: "Committee report",
      title: "Portfolio Committee Report on Sexual Harassment in Higher and Tertiary Education Institutions",
      publisher: "Parliament of Zimbabwe",
      date: "2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Sexual%20Harassment%20Report%20-%20Committee%20on%20Higher%20%26%20Tertiary%20Education%20%26%20Women%20Affairs.pdf",
      pages: 10,
      read: true,
      characters: 21967,
    },
    {
      id: "hedu-005",
      section: "Committee report",
      title: "Portfolio Committee on Higher and Tertiary Education, Science and Technological Development Report on Biotechnology (S.C. 1, 2016)",
      publisher: "Parliament of Zimbabwe",
      date: "2016",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Portfolio%20Committee%20on%20Higher%20and%20Tertiary%20Education%2C%20Science%20and%20Technological%20Development%27s%20Report%20on%20Biotechnology%20%28SC%201%2C%202016%29.pdf",
      pages: 14,
      read: true,
      characters: 29821,
    },
    {
      id: "hedu-006",
      section: "Governing law",
      title: "Manpower Planning and Development (Information Communication Technology Industry) Regulations, 2024 (S.I. 141 of 2024)",
      publisher: "Government of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202024-141%20Manpower%20Planning%20and%20Development%20%28Information%20Communication%20Technology%20Industry%29%20Regulations%2C%202024.pdf",
      pages: 32,
      read: true,
      characters: 41358,
    },
    {
      id: "hedu-007",
      section: "Governing law",
      title: "Manpower Planning and Development (Chemical Industry) Regulations, 2023 (S.I. 139 of 2023)",
      publisher: "Government of Zimbabwe",
      date: "2023",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202023-139%20Manpower%20Planning%20and%20Development%20%28Chemical%20Industry%29%20Regulations%2C%202023.pdf",
      pages: 20,
      read: true,
      characters: 27620,
    },
    {
      id: "hedu-008",
      section: "Bill",
      title: "Manpower Planning and Development Amendment Bill, 2020 (H.B. 2, 2020)",
      publisher: "Government of Zimbabwe",
      date: "2020",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Manpower%20Planning%20and%20Development%20Amendment%20Bill%202020.pdf",
      pages: 24,
      read: true,
      characters: 51688,
    },
  ],
  ict: [
    {
      id: "ict-001",
      section: "Sector policy",
      title: "Zimbabwe National Policy for Information and Communications Technology (ICT), 2016",
      publisher: "Ministry of Information Communication Technology, Postal and Courier Services",
      date: "2016",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Zimbabwe%20National%20Policy%20for%20ICT%202016.pdf",
      pages: 44,
      read: true,
      characters: 97927,
    },
    {
      id: "ict-002",
      section: "Governing law",
      title: "Cyber and Data Protection Act [Chapter 12:07] (No. 5 of 2021)",
      publisher: "Government of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Cyber%20%26%20Data%20Protection%20Act%20Cap1207%20No%205%20of%202021%20gaz%202022-03-11.pdf",
      pages: 38,
      read: true,
      characters: 94670,
    },
    {
      id: "ict-003",
      section: "Committee report",
      title: "Report of the Portfolio Committee on ICT, Postal and Courier Services on Mobile and Internet Connectivity in Zimbabwe (S.C. 9, 2024)",
      publisher: "Parliament of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/ICT%20Report%20on%20mobile%20and%20internet%20connectivity%20in%20Zimbabwe..pdf",
      pages: 12,
      read: true,
      characters: 23892,
    },
    {
      id: "ict-004",
      section: "Committee report",
      title: "Report of the Portfolio Committee on ICT, Postal and Courier Services: Benchmarking Visit to Rwanda (S.C. 6, 2021)",
      publisher: "Parliament of Zimbabwe",
      date: "October 2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/ICT%20PC%20Rwanda%20REPORT%20FINAL.pdf",
      pages: 10,
      read: true,
      characters: 14907,
    },
    {
      id: "ict-005",
      section: "Committee report",
      title: "First Report of the Portfolio Committee on ICT, Postal and Courier Services on the State of the Mobile Sector in Zimbabwe (S.C. 11, 2014)",
      publisher: "Parliament of Zimbabwe",
      date: "2014",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Portfolio%20Committee%20on%20ICT%20Postal%20and%20Courier%20Services%20on%20the%20State%20of%20the%20Mobile%20Sector%20in%20Zimbabwe%20-%20SC%2011-2014.pdf",
      pages: 10,
      read: true,
      characters: 21072,
    },
    {
      id: "ict-006",
      section: "Regulator guideline",
      title: "Cyber and Data Protection Implementation Guideline on Data Breach Notification and Handling (CDPG 3 of 2024)",
      publisher: "Postal and Telecommunications Regulatory Authority of Zimbabwe (POTRAZ)",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/03%20Data%20Breach%20Notification%20an%20handling.pdf",
      pages: 9,
      read: true,
      characters: 20973,
    },
    {
      id: "ict-007",
      section: "Regulator guideline",
      title: "Data Protection Authority Implementation Guidelines on the Cyber and Data Protection Act [Chapter 12:07]",
      publisher: "Postal and Telecommunications Regulatory Authority of Zimbabwe (POTRAZ)",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Cyber%20and%20Data%20Protection%20Act%20Implementation%20Guidlines.pdf",
      pages: 56,
      read: true,
      characters: 110558,
    },
    {
      id: "ict-008",
      section: "Regulator guideline",
      title: "Draft Consultation Paper on the Draft Amendment Bill to the Postal and Telecommunications Act [Chapter 12:05]",
      publisher: "Postal and Telecommunications Regulatory Authority of Zimbabwe (POTRAZ)",
      date: "March 2018",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Consultative%20Document%20on%20the%20Draft%20Bill%20March%202018.%20FINAL%20VERSION%20%20dd%2015....pdf",
      pages: 20,
      read: true,
      characters: 27518,
    },
  ],
  lg: [
    {
      id: "lg-001",
      section: "Governing law",
      title: "Urban Councils Act [Chapter 29:15]",
      publisher: "Government of Zimbabwe",
      date: "Published copy 2023-08",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Urban%20Councils%20Act%20%20%5BChapter%2029-15%5D.pdf",
      pages: 123,
      read: true,
      characters: 550596,
    },
    {
      id: "lg-002",
      section: "Governing law",
      title: "Provincial Councils and Administration Act [Chapter 29:11]",
      publisher: "Government of Zimbabwe",
      date: "Published copy 2021-05",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Provincial%20Councils%20%26%20Administration%20Act.pdf",
      pages: 13,
      read: true,
      characters: 52498,
    },
    {
      id: "lg-003",
      section: "Regulations",
      title: "Rural District Councils and Urban Councils (By-laws) (Repeal), 2026 (S.I. 90 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-090%20Rural%20District%20Councils%20and%20Urban%20Councils%20%28By-laws%29%20%28Repeal%29.pdf",
      pages: 6,
      read: true,
      characters: 7597,
    },
    {
      id: "lg-004",
      section: "Regulations",
      title: "Model Fees (Amendment) By-laws, 2026 (No. 1) (S.I. 89 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-089%20Model%20Fees%20%28Amendment%29%20By-laws%2C%202026%20%28No.%201%29.pdf",
      pages: 1,
      read: true,
      characters: 1671,
    },
    {
      id: "lg-005",
      section: "Regulations",
      title: "Minimum Service Delivery Standards Indicators for Local Authorities (Amendment) Regulations, 2026 (No. 1) (S.I. 69 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-069%20Minimum%20Service%20Delivery%20Standards%20Indicators%20for%20Local%20Authorities%20%28Amendment%29%20Regulations%2C%202026%20%28No.%201%29.pdf",
      pages: 8,
      read: true,
      characters: 9328,
    },
    {
      id: "lg-006",
      section: "Regulations",
      title: "Collective Bargaining Agreement: Rural District Councils Sector (S.I. 34 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-034%20Collective%20Bargaining%20Agreement%20Rural%20District%20Councils%20Sector.pdf",
      pages: 4,
      read: true,
      characters: 4883,
    },
  ],
  mfa: [
    {
      id: "mfa-001",
      section: "Committee report",
      title: "Fourth Report of the Portfolio Committee on Foreign Affairs and International Trade on the 2021 First, Second, Third and Fourth Quarter Budget Performance Reports for the Ministry of Foreign Affairs and International Trade",
      publisher: "Parliament of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REPORT%20OF%20THE%20PORTFOLIO%20COMMITTEE%20ON%20FOREIGN%20AFFAIRS%20AND%20INTERNATIONAL%20TRADE%20ON%20THE%202021%20BUDGET%20PERFOMANCE%20REPORTS%20FOR%20THE%20MINISTRY%20OF%20FOREIGN%20AFFAIRS%20AND%20INTERNATIONAL%20TRADE.pdf",
      pages: 12,
      read: true,
      characters: 20873,
    },
    {
      id: "mfa-002",
      section: "Committee report",
      title: "First Report of the Portfolio Committee on Foreign Affairs on Attracting Foreign Direct Investment (S.C. 6, 2015)",
      publisher: "Parliament of Zimbabwe",
      date: "2015",
      url: "https://www.veritaszim.net/sites/veritas_d/files/First%20Report%20of%20The%20Portfolio%20Committee%20on%20Foreign%20Affairs%20on%20Attracting%20Foreign%20Direct%20Investment.pdf",
      pages: 9,
      read: true,
      characters: 11664,
    },
    {
      id: "mfa-003",
      section: "Committee report",
      title: "Report of the Exchange Visit to Palestine by the Portfolio Committee on Foreign Affairs, 15–20 May 2016",
      publisher: "Parliament of Zimbabwe",
      date: "2016",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Report%20of%20the%20May%202016%20Exchange%20Visit%20to%20Palestine%20by%20the%20Portfolio%20Committee%20on%20Foreign%20Affairs.pdf",
      pages: 20,
      read: true,
      characters: 42669,
    },
    {
      id: "mfa-004",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Foreign Affairs and International Trade on the Virtual Conference held with the Foreign Affairs Committee of the National People's Congress of the People's Republic of China, 26 May 2021",
      publisher: "Parliament of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/CHINA%20VIRTUAL%20CONFERENCE%20FINAL%20REPORT.pdf",
      pages: 11,
      read: true,
      characters: 18410,
    },
    {
      id: "mfa-005",
      section: "Committee report",
      title: "Report of the Bilateral Visit to Russia by a Parliamentary Delegation led by the Speaker of the Parliament of the Republic of Zimbabwe",
      publisher: "Parliament of Zimbabwe",
      date: "2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REPORT%20OF%20THE%20BILATERAL%20VISIT%20TO%20RUSSIA%20BY%20A%20PARLIAMENTARY%20DELEGATION%20LED%20BY%20SPEAKER%20OF%20THE%20PARLIAMENT%20OF%20THE%20REPUBLIC%20OF%20ZIMBABWE.pdf",
      pages: 11,
      read: true,
      characters: 21384,
    },
    {
      id: "mfa-006",
      section: "Committee report",
      title: "Report on the Zimbabwe Parliamentary Delegation to Iran for the 6th International Conference in Support of the Palestinian Uprising, Teheran, 21–22 February 2017",
      publisher: "Parliament of Zimbabwe",
      date: "2017",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REPORT%20ON%20THE%20ZIMBABWE%20PARLIAMENTARY%20DELEGATION%20TO%20IRAN%20FOR%20THE%206TH%20INTERNATIONAL%20CONFERENCE%20IN%20SUPPORT%20OF%20PALESTINIAN%20UPRISING.pdf",
      pages: 12,
      read: true,
      characters: 18735,
    },
    {
      id: "mfa-007",
      section: "Committee report",
      title: "Report on the Parliamentary Delegation to the Osaka 2025 World Expo, 7–14 September 2025",
      publisher: "Parliament of Zimbabwe",
      date: "2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REPORT%20ON%20THE%20PARLIAMENTARY%20DELEGATION%20TO%20THE%20OSAKA%202025%20WORLD%20EXPO.pdf",
      pages: 27,
      read: true,
      characters: 31730,
    },
    {
      id: "mfa-008",
      section: "Committee report",
      title: "Report of the Delegation to the United Nations Office of Counter Terrorism High-Level Conference on Parliamentary Support to Victims of Terrorism, Rome, Italy, 7–8 June 2022",
      publisher: "Parliament of Zimbabwe",
      date: "2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REPORT%20ITALY-%20HIGH%20LEVEL%20CONFERENCE%20ON%20PARLIAMENTARY%20SUPPORT%20TO%20VICTIMS%20OF%20TERRORISM%20FINAL.pdf",
      pages: 14,
      read: true,
      characters: 28624,
    },
  ],
  mines: [
    {
      id: "mines-001",
      section: "Governing law",
      title: "Mines and Minerals Act [Chapter 21:05] (updated to 1 August 2021)",
      publisher: "Government of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Mines%20and%20Minerals%20Act%20Cap%2021-05%20updated%20to%201%20August%202021.pdf",
      pages: 126,
      read: true,
      characters: 577173,
    },
    {
      id: "mines-002",
      section: "Audit report",
      title: "Report of the Auditor-General on the Management of Occupational Health and Safety in Mining Operations (VFM 2019:05)",
      publisher: "Auditor-General, Republic of Zimbabwe",
      date: "2019",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Auditor-General%20Report%20on%20the%20Management%20of%20Occupational%20Health%20and%20Safety%20in%20Mining%20Operations%20by%20the%20Ministry%20of%20Mines%20and%20Mining%20Development.pdf",
      pages: 56,
      read: true,
      characters: 105994,
    },
    {
      id: "mines-003",
      section: "Committee report",
      title: "Report of the Portfolio Committee on Mines and Mining Development on a Self-Assessment of the Diamond Sector in Zimbabwe (S.C. 12, 2022)",
      publisher: "Parliament of Zimbabwe",
      date: "April 2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/REPORT%20OF%20THE%20PORTFOLIO%20COMMITTEE%20ON%20MINES%20AND%20MINING%20DEVELOPMENT%20ON%20A%20SELF-ASSESSMENT%20OF%20THE%20DIAMOND%20SECTOR%20IN%20ZIMBABWE%20FOURTH%20SESSION%20-%20NINTH%20PARLIAMENT%20APRIL%202022.pdf",
      pages: 14,
      read: true,
      characters: 27726,
    },
    {
      id: "mines-004",
      section: "Committee report",
      title: "First Report of the Portfolio Committee on Mines and Energy on the Consolidation of the Diamond Mining Companies (S.C. 9, 2017)",
      publisher: "Parliament of Zimbabwe",
      date: "2017",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Portfolio%20Committee%20on%20Mines%20and%20Energy%20Report%20on%20the%20Consolidation%20of%20the%20Diamond%20Mining%20Companies%20-%20SC%209-2017.pdf",
      pages: 21,
      read: true,
      characters: 44395,
    },
    {
      id: "mines-005",
      section: "Policy paper",
      title: "Lithium Mining and National Economic Development in Zimbabwe: Prospects for Resource-based National Development",
      publisher: "Green and Transition Minerals Collection (author: Grasian Mkodzongi)",
      date: "July 2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Lithium%20Mining%20and%20National%20Economic%20Development%20in%20Zimbabwe.pdf",
      pages: 24,
      read: true,
      characters: 77481,
    },
    {
      id: "mines-006",
      section: "Bill",
      title: "Mines and Minerals Bill, 2025 (H.B. 1, 2025)",
      publisher: "Government of Zimbabwe",
      date: "2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Mines%20%26%20Minerals%20Bill_0.pdf",
      pages: 396,
      read: true,
      characters: 1257618,
    },
    {
      id: "mines-007",
      section: "Governing law",
      title: "Base Minerals Export Control (Lithium Bearing Ores and Unbeneficiated Lithium) Order, 2022 (S.I. 213 of 2022)",
      publisher: "Government of Zimbabwe",
      date: "2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202022-213%20Base%20Minerals%20Export%20Control%20%28Lithium%20Bearing%20Ores%20and%20Unbeneficiated%20Lithium%29%20Order%2C%202022.pdf",
      pages: 2,
      read: true,
      characters: 3232,
    },
    {
      id: "mines-008",
      section: "Governing law",
      title: "Mines and Minerals (Prohibition Order of Exportations of Unprocessed Granite) Notice, 2022 (S.I. 127 of 2022)",
      publisher: "Government of Zimbabwe",
      date: "2022",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202022-127%20Mines%20and%20Minerals%20%28Prohibition%20Order%20of%20Exportations%20of%20Unprocessed%20Granite%29%20Notice%2C%202022.pdf",
      pages: 2,
      read: true,
      characters: 1912,
    },
  ],
  opc: [
    {
      id: "opc-001",
      section: "Governing law",
      title: "Constitution of Zimbabwe, 2013 (Amendment No. 20)",
      publisher: "Government of Zimbabwe",
      date: "2013",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Constitution%20of%20Zimbabwe%20Amendment%20%28No.%2020%29.pdf",
      pages: 151,
      read: false,
      characters: 0,
    },
    {
      id: "opc-002",
      section: "Governing law",
      title: "Constitution of Zimbabwe Amendment (No. 2) Act, 2021",
      publisher: "Government of Zimbabwe",
      date: "2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Constitution%20of%20Zimbabwe%20Amendment%20%28No.%202%29.pdf",
      pages: 10,
      read: true,
      characters: 23838,
    },
    {
      id: "opc-003",
      section: "State of the Nation Address",
      title: "State of the Nation Address by the President, 2024",
      publisher: "Office of the President and Cabinet",
      date: "2 October 2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/OPC%20SONA%20SPEECH%202024.pdf",
      pages: 21,
      read: true,
      characters: 18039,
    },
    {
      id: "opc-004",
      section: "State of the Nation Address",
      title: "State of the Nation Address by the President, 2023",
      publisher: "Office of the President and Cabinet",
      date: "3 October 2023",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SONA%20SPEECH%202023.pdf",
      pages: 19,
      read: true,
      characters: 17881,
    },
    {
      id: "opc-005",
      section: "Cabinet briefing",
      title: "Eleventh Post-Cabinet Press Briefing, 2025",
      publisher: "Zimbabwe Cabinet",
      date: "29 April 2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/ELEVENTH%20POST%20CABINET.pdf",
      pages: 10,
      read: true,
      characters: 12284,
    },
    {
      id: "opc-006",
      section: "Cabinet briefing",
      title: "Twelfth Post-Cabinet Press Briefing, 2025",
      publisher: "Zimbabwe Cabinet",
      date: "6 May 2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/TWELFTH%20POST%20CABINET%20BRIEF%202025%20-%206%20MAY%202025.pdf",
      pages: 10,
      read: true,
      characters: 12314,
    },
    {
      id: "opc-007",
      section: "State of the Nation Address",
      title: "President's 44th Independence Day Speech, 2024",
      publisher: "Office of the President and Cabinet",
      date: "18 April 2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/44TH%20INDEPENDENCE%20SPEECH%202024.pdf",
      pages: 28,
      read: true,
      characters: 19609,
    },
    {
      id: "opc-008",
      section: "State of the Nation Address",
      title: "State of the Nation Address, October 2021",
      publisher: "Office of the President and Cabinet",
      date: "7 October 2021",
      url: "https://www.veritaszim.net/sites/veritas_d/files/2021%20SONA%20OCTOBER.pdf",
      pages: 25,
      read: true,
      characters: 20725,
    },
  ],
  psc: [
    {
      id: "psc-001",
      section: "Bill",
      title: "State Service (Pensions) Bill, 2024 (H.B. 9, 2024)",
      publisher: "Government of Zimbabwe",
      date: "2024",
      url: "https://www.veritaszim.net/sites/veritas_d/files/H.B.%209%2C%202024%20State%20Service%20Pension%20Bill.pdf",
      pages: 34,
      read: true,
      characters: 86084,
    },
    {
      id: "psc-002",
      section: "Bill",
      title: "Public Service Amendment Bill, 2025 (H.B. 8, 2025)",
      publisher: "Government of Zimbabwe",
      date: "2025",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Public%20Service%20Amendment%20Bill%20H.B.%208%2C%202025.pdf",
      pages: 24,
      read: true,
      characters: 49677,
    },
    {
      id: "psc-003",
      section: "Governing law",
      title: "Public Entities Corporate Governance Act [Chapter 10:31] (No. 4 of 2018)",
      publisher: "Government of Zimbabwe",
      date: "2018",
      url: "https://www.veritaszim.net/sites/veritas_d/files/PUBLIC%20ENTITIES%20CORPORATE%20GOVERNANCE%20ACT_0.pdf",
      pages: 94,
      read: true,
      characters: 284371,
    },
    {
      id: "psc-004",
      section: "Regulations",
      title: "Public Entities Corporate Governance (General) Regulations, 2018 (S.I. 168 of 2018)",
      publisher: "Government of Zimbabwe",
      date: "2018",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202018-168%20Public%20Entities%20Corporate%20Governance%20%28General%29%20Regulations.pdf",
      pages: 22,
      read: true,
      characters: 34003,
    },
    {
      id: "psc-005",
      section: "Regulations",
      title: "Date of Commencement: Public Entities Corporate Governance Act [Chapter 10:31] (S.I. 89 of 2018)",
      publisher: "Government of Zimbabwe",
      date: "2018",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202018%20-%2089%20Date%20of%20Commencement%20Public%20Entities%20Corporate%20Governance%20Act.pdf",
      pages: 1,
      read: true,
      characters: 727,
    },
    {
      id: "psc-006",
      section: "Committee report",
      title: "Joint Portfolio Committee on Public Service, Labour and Social Welfare and the Thematic Committee on Human Rights: Report on the Petition by the Of Touch Institution (S.C. 18, 2026)",
      publisher: "Parliament of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/JOINT-PORTFOLIO-COMMITTEE-ON-PUBLIC-SERVICE-LABOUR-AND-SOCIAL-WELFARE-AND-THE-THEMATIC-COMMITTEE-ON-HUMAN-RIGHTS-PETITION-BY-THE-OF-TOUCH-INSTITUTION.pdf",
      pages: 10,
      read: true,
      characters: 19610,
    },
    {
      id: "psc-007",
      section: "Committee report",
      title: "Public Service, Labour and Social Welfare Portfolio Committee: First Report on the Administration of the Basic Education Assistance Module (S.C. 2, 2016)",
      publisher: "Parliament of Zimbabwe",
      date: "2016",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Public%20Service%2C%20Labour%20and%20Social%20Welfare%20Portfolio%20Committee%20Report%20on%20the%20Administration%20of%20the%20Basic%20Education%20Assistance%20Module%20-%20SC%202-2016.pdf",
      pages: 10,
      read: true,
      characters: 18785,
    },
  ],
  zida: [
    {
      id: "zida-001",
      section: "Governing law",
      title: "Zimbabwe Investment and Development Agency Act [Chapter 14:37] (Act No. 10 of 2019)",
      publisher: "Government of Zimbabwe",
      date: "2019",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Zimbabwe%20Investment%20and%20Development%20Agency%20Act%20-%20Act%2010-2019.pdf",
      pages: 40,
      read: true,
      characters: 111242,
    },
    {
      id: "zida-002",
      section: "Bill",
      title: "Zimbabwe Investment and Development Agency Bill, 2019 (H.B. 2, 2019)",
      publisher: "Government of Zimbabwe",
      date: "2019",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Zimbabwe%20Investment%20and%20Development%20Agency%20Bill%20-%20HB%202%2C%202019.pdf",
      pages: 48,
      read: true,
      characters: 114407,
    },
    {
      id: "zida-003",
      section: "Governing law",
      title: "Special Economic Zones Act [Chapter 14:34] (No. 7 of 2016)",
      publisher: "Government of Zimbabwe",
      date: "2016",
      url: "https://www.veritaszim.net/sites/veritas_d/files/Special%20Economic%20Zones%20Act%20%5BChapter%2014-34%5D.pdf",
      pages: 22,
      read: true,
      characters: 57138,
    },
    {
      id: "zida-004",
      section: "Regulations",
      title: "Zimbabwe Investment and Development Agency (Special Economic Zones) Regulations, 2023 (S.I. 226 of 2023)",
      publisher: "Government of Zimbabwe",
      date: "2023",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202023-226%20%20Zimbabwe%20Investment%20and%20Development%20Agency%20.pdf",
      pages: 18,
      read: true,
      characters: 30936,
    },
    {
      id: "zida-005",
      section: "Regulations",
      title: "Zimbabwe Investment and Development Agency (Special Economic Zones) (Amendment) Regulations, 2026 (No. 1) (S.I. 18 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-018%20Zimbabwe%20Investment%20and%20Development%20Agency%20%28Special%20Economic%20Zones%29%20%28Amendment%29%20Regulations%2C%202026%20%28No.%201%29.pdf",
      pages: 2,
      read: true,
      characters: 2892,
    },
    {
      id: "zida-006",
      section: "Regulations",
      title: "Zimbabwe Investment and Development Agency (General Investments) (Amendment) Regulations, 2026 (No. 1) (S.I. 17 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-017%20Zimbabwe%20Investment%20and%20Development%20Agency%20%28General%20Investments%29%20%28Amendment%29%20Regulations%2C%202026%20%28No.%201%29.pdf",
      pages: 2,
      read: true,
      characters: 1963,
    },
    {
      id: "zida-007",
      section: "Committee report",
      title: "Report of the Joint Portfolio Committees on Industry and Commerce and on Foreign Affairs and International Trade on the Zimbabwe Investment and Development Agency Bill, 16 July 2019",
      publisher: "Parliament of Zimbabwe",
      date: "2019",
      url: "https://www.veritaszim.net/sites/veritas_d/files/PC%20Report%20on%20ZIDA%20Bill%20-%2016%20July%202019%20_0001.pdf",
      pages: 11,
      read: true,
      characters: 20542,
    },
    {
      id: "zida-008",
      section: "General notice",
      title: "Amendment of a Special Economic Zone — General Notice 2086 of 2020, under the Zimbabwe Investment and Development Agency Act [Chapter 14:37]",
      publisher: "Government of Zimbabwe",
      date: "2020",
      url: "https://www.veritaszim.net/sites/veritas_d/files/GN%202086-2089%20SEZ%20Announcements.pdf",
      pages: 1,
      read: true,
      characters: 2765,
    },
  ],
  zimra: [
    {
      id: "zimra-001",
      section: "Regulations",
      title: "Customs and Excise (General) (Amendment) Regulations, 2026 (No. 130) (S.I. 130 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-130%20Customs%20and%20Excise%20%28General%29%20%28Amendment%29%20Regulations%2C%202026%20%28No.%20130%29.pdf",
      pages: 2,
      read: true,
      characters: 3916,
    },
    {
      id: "zimra-002",
      section: "Regulations",
      title: "Customs and Excise (Surtax Tariff) (Amendment) Notice, 2026 (S.I. 84 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-084%20Customs%20and%20Excise%20%28Surtax%20Tariff%29%20%28Amendment%29%20Notice%2C%202026.pdf",
      pages: 1,
      read: true,
      characters: 1469,
    },
    {
      id: "zimra-003",
      section: "Regulations",
      title: "Customs and Excise (Suspension) (Amendment) Regulations, 2026 (No. 286) (S.I. 74 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-074%20Customs%20and%20Excise%20%28Suspension%29%20%28Amendment%29%20Regulations%2C%202026%20%28No.%20286%29.pdf",
      pages: 4,
      read: true,
      characters: 5484,
    },
    {
      id: "zimra-004",
      section: "Regulations",
      title: "Customs and Excise (Furniture Manufacturer) (Amendment) Regulations, 2026 (No. 1) (S.I. 73 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-073%20Customs%20and%20Excise%20%28Furniture%20Manufacturer%29%20%28Amendment%29%20Regulations%2C%202026%20%28No.%201%29.pdf",
      pages: 1,
      read: true,
      characters: 1425,
    },
    {
      id: "zimra-005",
      section: "Regulations",
      title: "Customs and Excise (Printing and Packaging) (Suspension) (Amendment) Regulations, 2026 (No. 1) (S.I. 72 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-072%20Customs%20and%20Excise%20%28Printing%20and%20Packaging%29%20%28Suspension%29%20%28Amendment%29%20Regulations%2C%202026%20%28No.%201%29.pdf",
      pages: 1,
      read: true,
      characters: 1465,
    },
    {
      id: "zimra-006",
      section: "Regulations",
      title: "Customs and Excise (Printing and Packaging) (Suspension) Regulations, 2026 (S.I. 36A of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-036A%20Customs%20and%20Excise%20%28Printing%20and%20Packaging%29%20%28Suspension%29%20Regulations%2C%202026.pdf",
      pages: 12,
      read: true,
      characters: 20312,
    },
    {
      id: "zimra-007",
      section: "Regulations",
      title: "Customs and Excise (Suspension) (Amendment) Regulations, 2026 (No. 285) (S.I. 36 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-036%20Customs%20and%20Excise%20%28Suspension%29%20%28Amendment%29%20Regulations%2C%202026%20%28No.%20285%29.pdf",
      pages: 2,
      read: true,
      characters: 2598,
    },
    {
      id: "zimra-008",
      section: "Regulations",
      title: "Customs and Excise (General) (Amendment) Regulations, 2026 (No. 129) (S.I. 15 of 2026)",
      publisher: "Government of Zimbabwe",
      date: "2026",
      url: "https://www.veritaszim.net/sites/veritas_d/files/SI%202026-015%20Customs%20and%20Excise%20%28General%29%20%28Amendment%29%20Regulations%2C%202026%20%28No.%20129%29.pdf",
      pages: 1,
      read: true,
      characters: 1677,
    },
  ],
};
